name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: fix git
      run: git config --global url.https://github.com/.insteadOf git://github.com/

    - name: dependencies
      run: ./prepare-depends.sh

    - name: build snarky
      run: cd snarky && make -j
