name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dependencies
      run: ./prepare-depends.sh

    - name: build snarky
      run: cd snarky && make -j
